In [1]:
import numpy as np
import cv2
import os

In [2]:
def DrawPolygon(pts, image):
    if len(pts) == 0:
        pass
    else:
        pts = np.array(pts, dtype=np.uint64)
        pts = pts.reshape((-1, 1, 2))
        isClosed = True
        color = (255, 0, 0)
        thickness = 2
        image = cv2.polylines(image, [pts],
                            isClosed, color, thickness)
        return image, pts

In [3]:
def GetPoints(img):
    a = []

    def click_event(event, x, y, flags, params):
        if event == cv2.EVENT_LBUTTONDOWN:
            cv2.circle(img, (x,y), radius=2, color=(0, 0, 255), thickness=-1)
            print(x, ' ', y)
            cv2.imshow('Assessing', img)
        if event==cv2.EVENT_LBUTTONDOWN:
            a.append((x,y))

    cv2.imshow('Assessing', img)
    cv2.setMouseCallback('Assessing', click_event)
    print('press "Esc" after labeling finished')
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    return np.array(a, dtype=np.uint64)

In [4]:
def showing(image, mask, polygons):
    for poly in polygons:
        image, poly = DrawPolygon(poly, image)
        mask = cv2.fillPoly(mask, [poly], color)
    cv2.imshow('image', image)
    cv2.imshow('mask', mask)

In [5]:
path = 'SEMSamples'
k = 0.5
files = os.listdir(path)
images = []
for file in files:
    if file.split('.')[-1] in ['tif','jpg', 'jpeg', 'png']:
        images.append(file)
print(images)

for imge in images:
    img = cv2.imread(f'{path}/{imge}')
    mask = np.zeros((img.shape[0],img.shape[1]), dtype=np.uint8)
    image = cv2.resize(img, (0, 0), fx=k, fy=k, interpolation=cv2.INTER_LINEAR)
    mask = cv2.resize(mask, (0, 0), fx=k, fy=k, interpolation=cv2.INTER_LINEAR)
    polygons = []
    while True:
        # showing(image, mask, polygons)
        pts = GetPoints(image)
        if len(pts) != 0:
            image, pts = DrawPolygon(pts, image)
        color = (255, 255, 255)
        print(f'pts: {pts}')
        if len(pts) != 0:
            polygons.append(pts)
        mask = np.zeros((image.shape[0],image.shape[1]), dtype=np.uint8)
        showing(image, mask, polygons)
        print(f'polygons len: {len(polygons)}')
        print('press "d" for deleting the last polygon')
        if cv2.waitKey(0) == ord('d'):
            if len(polygons) != 0:
                polygons.pop()
        print(f'polygons len: {len(polygons)}')
        # image = cv2.imread(f'SEMSamples/{img}')
        mask = np.zeros((image.shape[0],image.shape[1]), dtype=np.uint8)
        showing(image, mask, polygons)
        print('press "f" for finishing labeling current image')
        if cv2.waitKey(0) == ord('f'):
            break
    
    image = cv2.resize(image, (0, 0), fx=(1/k), fy=(1/k), interpolation=cv2.INTER_LINEAR)
    mask = cv2.resize(mask, (0, 0), fx=(1/k), fy=(1/k), interpolation=cv2.INTER_LINEAR)
    cv2.imwrite(f'{path}/mask_{imge}', mask)
    print('press "b" for breaking the operation')
    if cv2.waitKey(0) == ord('b'):
        break


['1.jpg', '2.jpg', 'mask_1.jpg', 'mask_2.jpg', 'mask_mask_1.jpg', 'mask_mask_2.jpg']
press "Esc" after labeling finished
469   102
269   97
406   281
pts: [[[469 102]]

 [[269  97]]

 [[406 281]]]
polygons len: 1
press "d" for deleting the last polygon
polygons len: 1
press "f" for finishing labeling current image
press "Esc" after labeling finished
347   276
243   181
226   337
pts: [[[347 276]]

 [[243 181]]

 [[226 337]]]
polygons len: 2
press "d" for deleting the last polygon
polygons len: 2
press "f" for finishing labeling current image
press "Esc" after labeling finished
164   104
180   135
87   219
pts: [[[164 104]]

 [[180 135]]

 [[ 87 219]]]
polygons len: 3
press "d" for deleting the last polygon
polygons len: 2
press "f" for finishing labeling current image
press "Esc" after labeling finished
pts: []
polygons len: 2
press "d" for deleting the last polygon
polygons len: 1
press "f" for finishing labeling current image
press "Esc" after labeling finished
pts: []
polygons len: 